title: aednlaxer
url: https://aednlaxer.github.io
baseurl: ""
permalink: pretty

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

paginate: 10

markdown: kramdown

sass:
  sass_dir: css
  style: :compressed

author:
  name: Alexander

version: 3.0.0
