name: aednlaxer_blog
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  intl: ^0.20.2
  jaspr: ^0.21.3
  jaspr_content: ^0.4.1
  jaspr_router: ^0.7.3
  path: ^1.9.0
  syntax_highlight_lite: ^0.0.1

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.2.3+1
  jaspr_builder: ^0.21.3
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: static
