name: Publish website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Dart"
        uses: dart-lang/setup-dart@v1.3

      - name: "Build Jaspr"
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          path: "build/jaspr"
